config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: "posts#index"
 	 resources :posts do
  	resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  #This validates presence of title, and makes sure that the length is not more than 140 words
  validates :title, presence: true, length: {maximum: 140}
  #This validates presence of body
  validates :body, presence: true
  has_many :comments, dependent: :destroy
end

app/models/retard.rb
class Retard < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy
   #mount avatar uploader
  mount_uploader :avatar, AvatarUploader
end
	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?
    

  protected

  #configure permitted parameters for devise
  def configure_permitted_parameters
    added_attrs = [:email, :password, :password_confirmation, :remember_me, :avatar, :avatar, :avatar_cache]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

   def destroy
    if @comment.destroy
      flash[:notice] = "Successfully deleted post!"
	  redirect_to post_path(@post)
    else
      flash[:alert] = "Error deleting post!"
    end
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

  redirect_to post_path(@post)
end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :destroy]

  # Index action to render all posts
  def index
    @posts = Post.all
  end

  # New action for creating post
  def new
    @post = Post.new
  end

  # Create action saves the post into database
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
 def edit
    @post = Post.find(params[:id])
  end

  # Update action updates the post with the new information
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params) 
        redirect_to post_path(@post)
        # redirect_to(:action => 'posts#show')
    else
        render 'edit'
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error deleting post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end

    #This authenticates admin whenever a post is to be created, updated or destroyed.
 	 before_action :authenticate_user!, except: [:index, :show]
end

app/controllers/retards_controller.rb
class RetardsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/helpers/retards_helper.rb
module RetardsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f|%>
<%= f.text_area :content %>
<br>
<%= f.submit %>
<% end %> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class = "navback">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand">Blog</a>
    </div>
          <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? %>
        <!--This block is only visible to signed in users -->
          <li><%= link_to 'New Post', new_post_path %></li>
          <li><%= link_to 'My Account', edit_user_registration_path  %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
        <!-- The block ends here -->
        <% else %>
          <li><%= link_to 'Login', new_user_session_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'posts', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Render navigation bar -->
  <%= render "layouts/navigation" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container-fluid">
    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb

<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class= "main">
<h1>Edit Article</h1>
<br>
<center><%= render 'posts/form' %></center>
<%= link_to "Back", :back, class: "btn btn-primary btn-md" %>
</div>

app/views/posts/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<div class= "main">
  <br>
<h1>Welcome to the Blog!</h1>
  <br>
<div class="container">
  <div class="col-sm-10 col-sm-offset-1 col-md-1100">
    <% @posts.each do |post| %>
    <div class="col-xs-12 text-center">
      <div class="text-center">
        <h2><strong><%= post.title %></strong></h2>
        <h6><%= post.created_at.strftime('%b %d, %Y') %></h6>
      </div>
      <div>
        <%= raw(post.body).truncate(358) %>
      </div>
       <br>
      <div> 
       <%= link_to "Show", post_path(post), class: "btn btn-warning active btn-md" %>
        <br>
        <br>
      </div>
      <% if user_signed_in? %>
        <%= link_to "Edit", edit_post_path(post), class: "btn btn-primary active btn-md" %>
        <br>
        <br>
        <%= link_to "Delete", post_path(post), class: "btn btn-danger active btn-md", data: {:confirm => "Are you sure?"}, method: :delete %>
      <% end %>
      <hr />
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/posts/new.html.erb
	
<div class = "back">
<div class="container">
 <div class="col-sm-10 col-sm-offset-1 col-xs-12">
<br>
<br>
<h1><center>Create New Post</center></h1>
<%= render "posts/form" %>
  <%= link_to "Back", posts_path, class: "btn btn-primary btn-md" %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</div>
</div>
</div>

app/views/posts/show.html.erb
<div class =  "main">
<div class ="container">
  <br>
  <h1><strong><%= @post.title %></strong></h1>
  <p><center><%= @post.created_at.strftime('%b %d, %Y') %></center></p>
  	<br>
  <center><%= raw @post.body %></center>
  <br>
  <br>
    <strong><center>Comments</center></strong>
    <br>
  <% @post.comments.each do |comment| %>
     <p>
      <strong><%= comment.commenter %></strong>
    </p>
    <p>
      <%= comment.body %><br>
    </p>
    <% if user_signed_in? %>  
    <%= link_to 'Delete Comment',post_comment_path(@post, comment),method: :delete,data: { confirm: 'Are you sure?' } %>
  <% end %>
  <% end %>
<br
><br>
  <% if user_signed_in? %>  
    <strong><center>Add Comment</center></strong>
  <%= form_for([@post, @post.comments.build]) do |f| %>
      <p><center>
      <%= f.label :commenter %>:
      <%= f.text_field :commenter %>
    </center></p>
    <p><center>
      <%= f.text_area :body %>
    </p></center>
    <p><center>
      <%= f.submit "Create Comment", :id => "save-button" %>
    </p></center>
  <% end %>
  <% else %>
    <center><%= link_to 'Login/Register to add new comments', new_user_session_path%>
    </center>
  <% end %>
  <br>
  <%= link_to "Back", posts_path, class: "btn btn-primary btn-md" %>
</div>
</div>

app/views/users/shared/_links.html.erb
<div class="col-sm-offset-4 col-sm-4 col-xs-12">
  <% if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</div>